name: PR Email Notification

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.yourmailserver.com
        server_port: 587
        username: ${{ secrets.SMTP_USER }}
        password: ${{ secrets.SMTP_PASS }}
        subject: "📬 New PR to main: ${{ github.event.pull_request.title }}"
        to: you@example.com
        from: CI Bot <ci@example.com>
        body: |
          A new pull request was created:
          - Title: ${{ github.event.pull_request.title }}
          - Author: ${{ github.event.pull_request.user.login }}
          - URL: ${{ github.event.pull_request.html_url }}
